services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:front

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile-front -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  only:
    - master
  script:
    - upgrade --environment staging --stack pca-finder --service meteor
