services:
  - docker:dind

variables:
  IMAGE_METEOR_TAG: $CI_REGISTRY_IMAGE:live-front
  IMAGE_MODEL_TAG: $CI_REGISTRY_IMAGE:live-models

build-meteor:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile-front -t $IMAGE_METEOR_TAG .
    - docker push $IMAGE_METEOR_TAG

build-models:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile-model -t $IMAGE_MODEL_TAG .
    - docker push $IMAGE_MODEL_TAG