FROM python:3.6-slim-buster

# set work directory
WORKDIR /webapps/pcad

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY models models

RUN pip install -r models/requirements.txt

RUN pip install gunicorn

# chown all the files to the app user
RUN chown -R www-data:www-data .

# Change current user to www-data
USER www-data

EXPOSE 5000

# CMD ["python", "models/pcad.py"]

CMD [ "gunicorn", "-w", "3", "--bind", "0.0.0.0:5000", "wsgi"]
