version: '2'
services:
  orthanc:
    image: jodogne/orthanc-plugins
    volumes:
      - /srv/docker/local/orthanc-db/:/var/lib/orthanc/db/
    ports:
      - 4242:4242
      - 8042:8042
  pcad:
    build:
      context: .
      dockerfile: Dockerfile-model
    volumes:
      - /dali/rcc/appdev/pca-finder/data:/data
    ports:
      - 5000:5000
  meteor:
    build:
      context: .
      dockerfile: Dockerfile-front
    environment:
      METEOR_SETTINGS: |-
        {
                  "servers": {
                    "dicomWeb": [
                      {
                        "name": "Orthanc",
                        "wadoUriRoot": "http://localhost:8042/wado",
                        "qidoRoot": "http://localhost:8042/dicom-web",
                        "wadoRoot": "http://localhost:8042/dicom-web",
                        "qidoSupportsIncludeField": false,
                        "imageRendering": "wadouri",
                        "thumbnailRendering": "wadors",
                        "requestOptions": {
                          "auth": "orthanc:orthanc",
                          "logRequests": true,
                          "logResponses": false,
                          "logTiming": true
                        }
                      }
                    ]
                  },
                  "defaultServiceType": "dicomWeb",
                  "dropCollections": true,
                  "public": {
                    "verifyEmail": false,
                    "ui": {
                        "studyListFunctionsEnabled": true,
                        "leftSidebarOpen": false,
                        "displaySetNavigationLoopOverSeries": false,
                        "displaySetNavigationMultipleViewports": true,
                        "autoPositionMeasurementsTextCallOuts": "TRLB"
                    }
                  },
                  "proxy": {
                    "enabled": true
                  }
                }
      MONGO_OPLOG_URL: mongodb://oplogger:mongoadmin@mongodb/local?authSource=admin
      MONGO_URL: mongodb://meteor:mongoadmin@mongodb/meteor
      ROOT_URL: http://pca-finder.staging.rcc.uchicago.edu
    ports:
      - 80:3000
    links:
    - mongodb
  mongodb:
    image: tozd/meteor-mongodb:3.4
    environment:
      MONGODB_ADMIN_PWD: mongoadmin
      MONGODB_CREATE_PWD: mongoadmin
      MONGODB_OPLOGGER_PWD: mongoadmin    