version: '2'
services:
  orthanc:
    image: jodogne/orthanc-plugins
    volumes:
    - /srv/docker/local/orthanc-db/:/var/lib/orthanc/db/
    - /dali/rcc/appdev/pca-finder/orthanc-settings/orthanc.json:/etc/orthanc/orthanc.json
    labels:
      io.rancher.container.pull_image: always
  pcad:
    image: docker-images.rcc.uchicago.edu/app-dev-group/pca-finder:models
    volumes:
    - /dali/rcc/appdev/pca-finder/data:/data
    labels:
      io.rancher.container.pull_image: always
  meteor:
    image: docker-images.rcc.uchicago.edu/app-dev-group/pca-finder:front
    environment:
      ROOT_URL: https://pca-finder.rcc.uchicago.edu
      MONGO_URL: mongodb://meteor:mongoadmin@mongodb/meteor
      MONGO_OPLOG_URL: mongodb://oplogger:mongoadmin@mongodb/local?authSource=admin
      METEOR_SETTINGS: |-
        {
                  "servers": {
                    "dicomWeb": [
                      {
                        "name": "Orthanc",
                        "wadoUriRoot": "https://pca-finder.rcc.uchicago.edu:8042/wado",
                        "qidoRoot": "https://pca-finder.rcc.uchicago.edu:8042/dicom-web",
                        "wadoRoot": "https://pca-finder.rcc.uchicago.edu:8042/dicom-web",
                        "qidoSupportsIncludeField": false,
                        "imageRendering": "wadouri",
                        "thumbnailRendering": "wadors",
                        "requestOptions": {
                          "auth": "pcafinder:pcafinder",
                          "logRequests": true,
                          "logResponses": false,
                          "logTiming": true
                        }
                      }
                    ]
                  },
                  "defaultServiceType": "dicomWeb",
                  "dropCollections": true,
                  "public": {
                    "verifyEmail": false,
                    "ui": {
                        "studyListFunctionsEnabled": true,
                        "leftSidebarOpen": false,
                        "displaySetNavigationLoopOverSeries": false,
                        "displaySetNavigationMultipleViewports": true,
                        "autoPositionMeasurementsTextCallOuts": "TRLB"
                    }
                  },
                  "proxy": {
                    "enabled": true
                  }
                }
    links:
    - mongodb:mongodb
    labels:
      io.rancher.container.pull_image: always
  nginx-redirect-to-https:
    image: nginx:stable
    labels:
      io.rancher.container.pull_image: always
  mongodb:
    image: tozd/meteor-mongodb:3.4
    environment:
      MONGODB_ADMIN_PWD: mongoadmin
      MONGODB_CREATE_PWD: mongoadmin
      MONGODB_OPLOGGER_PWD: mongoadmin
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always